name: tissue-model-human-intestine
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-seurat=4.1.0
  - r-seuratobject=4.0.4
  - bioconductor-rhdf5=2.38.0
  - bioconductor-scran=1.22.1
  - bioconductor-bluster=1.4.0
  - bioconductor-aucell=1.16.0
  - bioconductor-clusterProfiler=4.2.0
  - bioconductor-org.hs.eg.db=3.14.0
  - r-docopt=0.7.1
  - r-viridis=0.6.2
  - r-uwot=0.1.11
  - leidenalg=0.8.9
  - r-leiden=0.3.9
  - r-pheatmap=1.0.12
  - r-readxl=1.3.1
